### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Yehonal** [Desch/Character-Migration#1]
Would be nice to split the addon inside another repository IMHO.

**Comment by Desch** [comment]
Hi, how are you.

I don't understand why you want to split the addon in other repository.
The addon is only the .rar.

**Comment by Yehonal** [comment]
In this way we can fix / improve things about it. Or even create branches
to suppport other client versions. A rar is not a good way to keep sources
in a repository :)
Il 10/Ago/2015 19:39, "LM" <notifications@github.com> ha scritto:

**Comment by Desch** [comment]
Yep, you are right.
So, I'm going to upload the addon in other folder.

Thanks for the suggestion.

**Comment by Yehonal** [comment]
:+1: :)

however we should also keep this rar file in this folder ( and keep updated eventually ) since it is required by playerside.php since there's a download link anchored to it

take a look at $write[51] here: https://github.com/Desch/Character-Migration/blob/21c2067d5d5a453461a8706bf44b61383c0dfcbd/_transfer/language.php

we need both repository and rar IMHO :)
